# Generated by Django 4.2.18 on 2025-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug_medication', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frecuency', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('isactive', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('typeformat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medications',
            },
        ),
    ]
