# Generated by Django 4.2.18 on 2025-01-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(blank=True, db_column='id_role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='role.role')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='user.user')),
            ],
            options={
                'db_table': 'userrole',
            },
        ),
    ]
