# Generated by Django 4.2.18 on 2025-01-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_activity', models.ForeignKey(blank=True, db_column='id_activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
                ('id_img', models.ForeignKey(blank=True, db_column='id_img', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_images', to='images.images')),
            ],
            options={
                'db_table': 'imagesactivities',
            },
        ),
    ]
