# Generated by Django 4.2.18 on 2025-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('card_date', models.CharField(max_length=255)),
                ('ccv', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isactive', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_inscription', models.ForeignKey(blank=True, db_column='id_inscription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inscription.inscription')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
