# Generated by Django 4.2.18 on 2025-01-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('year', '0001_initial'),
        ('hour', '0001_initial'),
        ('month', '0001_initial'),
        ('day', '0001_initial'),
        ('daysofweek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_activitie', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('isactive', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('intensity', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caracteristics', models.JSONField(default=dict)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('max_participants', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('id_day', models.ForeignKey(blank=True, db_column='id_day', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_by_day', to='day.day')),
                ('id_dayoftheweek', models.ForeignKey(blank=True, db_column='id_dayoftheweek', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_by_dayoftheweek', to='daysofweek.dayofweek')),
                ('id_hour', models.ForeignKey(blank=True, db_column='id_hour', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_by_hour', to='hour.hour')),
                ('id_month', models.ForeignKey(blank=True, db_column='id_month', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_by_month', to='month.month')),
                ('id_year', models.ForeignKey(blank=True, db_column='id_year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_by_year', to='year.year')),
                ('activity_type', models.SmallIntegerField(choices=[(1, 'Cuidados'), (2, 'Exteriores'), (3, 'Rehabilitaciónes'), (4, 'Relajación'), (5, 'Educación')])),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-createdat'],
            },
        ),
    ]
