# Generated by Django 4.2.18 on 2025-01-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('hour', '0001_initial'),
        ('userpatient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('isactive', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_medication', models.ForeignKey(blank=True, db_column='id_medication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medications.medications')),
                ('id_patient', models.ForeignKey(blank=True, db_column='id_patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='userpatient.userpatient')),
                ('start_hour', models.ForeignKey(blank=True, db_column='id_hour', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hour.hour')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
