# Generated by Django 4.2.18 on 2025-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancelation', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelation',
            name='id_inscription',
            field=models.ForeignKey(blank=True, db_column='id_inscription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelations', to='inscription.inscription'),
        ),
    ]
