# Generated by Django 4.2.18 on 2025-01-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name_diet', models.CharField(max_length=255)),
                ('allergens', models.JSONField()),
                ('isactive', models.IntegerField()),
                ('healthy_scale', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('days', models.JSONField()),
                ('description', models.CharField(max_length=255)),
                ('id_breakfast', models.ForeignKey(blank=True, db_column='id_breakfast', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_diets', to='meals.meals')),
                ('id_dessert', models.ForeignKey(blank=True, db_column='id_dessert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessert_diets', to='meals.meals')),
                ('id_dinner', models.ForeignKey(blank=True, db_column='id_dinner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_diets', to='meals.meals')),
                ('id_lunch', models.ForeignKey(blank=True, db_column='id_lunch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_diets', to='meals.meals')),
                ('id_snack', models.ForeignKey(blank=True, db_column='id_snack', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snack_diets', to='meals.meals')),
            ],
            options={
                'db_table': 'diets',
            },
        ),
    ]
