# Generated by Django 4.2.18 on 2025-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('userpatient', '0001_initial'),
        ('day', '0001_initial'),
        ('month', '0001_initial'),
        ('hour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('isactive', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=50)),
                ('special_request', models.CharField(max_length=255)),
                ('id_activity', models.ForeignKey(blank=True, db_column='id_activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='activities.activity')),
                ('id_day', models.ForeignKey(blank=True, db_column='id_day', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='day.day')),
                ('id_hour', models.ForeignKey(blank=True, db_column='id_hour', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='hour.hour')),
                ('id_month', models.ForeignKey(blank=True, db_column='id_month', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='month.month')),
                ('id_patient', models.ForeignKey(blank=True, db_column='id_patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='userpatient.userpatient')),
            ],
            options={
                'db_table': 'inscriptions',
            },
        ),
    ]
