# Generated by Django 4.2.18 on 2025-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('user', '0001_initial'),
        ('inscription', '0001_initial'),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='id_payment',
            field=models.OneToOneField(blank=True, db_column='id_payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='user.user'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='id_year',
            field=models.ForeignKey(blank=True, db_column='id_year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='year.year'),
        ),
    ]
