# Generated by Django 4.2.18 on 2025-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(max_length=50)),
                ('num_room', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('isactive', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
